mame: stop using system lua
lua 5.4 has changed signature of lua_resume causing:
| ../../../../../src/frontend/mame/luaengine.cpp: In member function 'void lua_engine::resume(void*, int)':
| ../../../../../src/frontend/mame/luaengine.cpp:1871:30: error: too few arguments to function 'int lua_resume(lua_State*, lua_State*, int, int*)'
|  1871 |         int stat = lua_resume(L, nullptr, 0);
|       |                    ~~~~~~~~~~^~~~~~~~~~~~~~~

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>